server:
  port: 8080
spring:
  datasource: 
    druid: 
      url: jdbc:mysql://192.168.0.131:3306/he_campus_dwz?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      filter: 
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-log-enabled: false
  redis:
    host: 192.168.0.131
    port: 6379
    timeout: 3000
logging:
  level:
    druid.sql.Statement: DEBUG